### ISSUE TITLE
NullPointerException in analytics kit

### ISSUE THREAD

**Issue by SalsabeelaHasan** [HMS-Core/hms-flutter-plugin#142]
**Description**
I did a Huawei Analytics kit Implementation recently and made sure that all the data is uploaded to the analysis console without any problem, but I was surprised by the presence of this exception : 
***Attempt to read from field 'java.lang.String com.huawei.hms.analytics.ar.ghi' on a null object reference***
through Firebase Crashlytics after we started using **a release version**... But I still do not understand what the problem is and how to solve it.
noting that: I confirm that there is no indication that there is any problem when using debug mode or when reviewing the analysis console.

**Environment**
 - Platform: Flutter
 - Kit: huawei_analytics
 - Kit Version : ^6.2.0+301
 - OS :  Android 
 
**Logs**
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.huawei.hms.analytics.ar.ghi' on a null object reference
       at com.huawei.hms.analytics.ijk.klm(ijk.java:14)
       at com.huawei.hms.analytics.a$2.run(a.java:72)
       at android.os.Handler.handleCallback(Handler.java:809)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7555)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)

**Comment by furkansarihan** [comment]
Hi @SalsabeelaHasan,

This exception resolved with Huawei Analytics SDK 6.3.0.303.

We'll update this package with new Analytics SDK version in our next major release.  Keep an eye on [pub.dev](https://pub.dev/packages/huawei_analytics) for updates.

### For Quick Fix;

You can fork the repo and change the Analytics SDK version at line 44 in `android/build.gradle` to 6.3.0.303.

``` gradle
dependencies {
    implementation 'com.huawei.hms:hianalytics:6.3.0.303'
}
```
