### ISSUE TITLE
 java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.Context.sendBroadcast(android.content.Intent)' on a null object reference

### ISSUE THREAD

**Issue by smlertek** [HMS-Core/hms-flutter-plugin#15]
When the App is killed and we send a DataMessage the app crashed and shows the following error in logcat 

```
09-15 16:20:50.807 9020-9020/pushit.lertek E/AndroidRuntime: FATAL EXCEPTION: main
    Process: pushit.lertek, PID: 9020
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.Context.sendBroadcast(android.content.Intent)' on a null object reference
        at com.huawei.hms.flutter.push.utils.Utils.sendIntent(Utils.java:55)
        at com.huawei.hms.flutter.push.hms.FlutterHmsMessageService.onMessageReceived(FlutterHmsMessageService.java:45)
        at com.huawei.hms.push.HmsMessageService.a(HmsMessageService.java:149)
        at com.huawei.hms.push.HmsMessageService.a(HmsMessageService.java:34)
        at com.huawei.hms.push.HmsMessageService$a.handleMessage(HmsMessageService.java:126)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
```
We tried in this mobile phone **HUAWEI Y7P**  Android **9.0**

**Comment by aktug** [comment]
Hello @smlertek , we`re working to solve this issue

**Comment by aktug** [comment]
Hello @smlertek , we`re working to solve this issue, when App isn`t running if a data message will be received, App crashes. We`ll fix it and publish a new version as soon as possible 👍

**Comment by smlertek** [comment]
Thanks, i will wait for the next version that solves this issue
