### ISSUE TITLE
[flutter-hms-iap] 处理onActivityResult不合理

### ISSUE THREAD

**Issue by nullptrX** [HMS-Core/hms-flutter-plugin#17]
```
/AndroidRuntime(21409): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=64206, result=-1, data=Intent { (has extras) }} to activity {cn.quickcn.android.huawei/cn.quickcn.android.MainActivity}: java.lang.NullPointerException
E/AndroidRuntime(21409): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4845)
E/AndroidRuntime(21409): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
E/AndroidRuntime(21409): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(21409): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(21409): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(21409): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
E/AndroidRuntime(21409): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(21409): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(21409): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(21409): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21409): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
E/AndroidRuntime(21409): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime(21409): Caused by: java.lang.NullPointerException
E/AndroidRuntime(21409): 	at java.util.Objects.requireNonNull(Objects.java:203)
E/AndroidRuntime(21409): 	at com.huawei.hms.flutter.iap.MethodCallHandlerImpl.onActivityResult(MethodCallHandlerImpl.java:234)
E/AndroidRuntime(21409): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:691)
E/AndroidRuntime(21409): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:378)
E/AndroidRuntime(21409): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:619)
E/AndroidRuntime(21409): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:584)
E/AndroidRuntime(21409): 	at android.app.Activity.dispatchActivityResult(Activity.java:8131)
E/AndroidRuntime(21409): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
E/AndroidRuntime(21409): 	... 11 more
```

如果存在其他三方回调onActivityResult, 必抛空指针异常。

**Comment by aktug** [comment]
你好 @nullptrX , 哪个工具包 ?

**Comment by nullptrX** [comment]
你好，日志中有包名。`com.huawei.hms.flutter.iap.MethodCallHandlerImpl.onActivityResult`

```yaml
flutter-hms-iap: ^5.0.0+300
```

**Comment by nullptrX** [comment]
因为Flutter应用基本都是共用一个Activity，所有实现了`onActivityResult`的回调都会走一遍。

**Comment by aktug** [comment]
@nullptrX 你有什么建议 ? 你能给我们更多关于这个的信息吗 ?

**Comment by nullptrX** [comment]
<img src="https://cdn.jsdelivr.net/gh/nullptrX/assets/images/20200924234617.png" width="500"/>

上图是`Facebook`登录成功后的回调到`MethodCallHandlerImpl`中的断点调试。由于代码中使用了`Objects.requireNonNull`方法，所以这里必然会出现空指针异常。建议改动如下（二选一）

1. 仅处理自己请求码的回调
```java
    public boolean onActivityResult(int requestCode, int resultCode, Intent data) {
        // add code here
        if (requestCode != REQUEST_CREATE_PURCHASE_INTENT && requestCode != REQUEST_IS_ENVIRONMENT_READY) {
            return false;
        }
        
        final Result result = Objects.requireNonNull(mResultsForRequests.get(requestCode)).first;
        ...
```
2. 非空处理
```java
    public boolean onActivityResult(int requestCode, int resultCode, Intent data) {
        // use following code instead
        Pair<Result, Integer> pair = mResultsForRequests.get(requestCode);
        if (pair == null) {
            return false;
        }
        
        final Result result = pair.first;
        final int requestType = pair.second;
        ...
```

**Comment by nullptrX** [comment]
综上，即是处理不了的数据不能抛异常出去，`return false`就好。

**Comment by aktug** [comment]
谢谢@nullptrX，我们将在 10 月底的下一个版本中解决此问题, 多谢 👍
