### ISSUE TITLE
应用无法上架小米应用商店，使用huawei_push,似乎在应用启动时会获取android id和ip地址

### ISSUE THREAD

**Issue by tenutos** [HMS-Core/hms-flutter-plugin#181]
以前都是正常上架（集成huawei_push已经半年了），大约从2周前小米应用商店频繁给我发消息，说在请求用户授权前，违规获取android id和ip地址。

这是他们提供的运行堆栈：
1、应用内存在隐私不合规的行为：用户授权同意前，违规收集 Android id、ip地址等信息。
发生时间 ：2022-04-25 09:30:40 738		索引 ：100000021
2b3560fffa5922b3
调用SDK：flutter插件
调用堆栈：
	android.provider.Settings$Secure.getStringForUser:4987
	android.provider.Settings$Secure.getString:4934
	i.a.a.a.b.a:4
	i.a.a.a.b.onMethodCall:188
	io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage:17
	io.flutter.embedding.engine.dart.DartMessenger.invokeHandler:18
	io.flutter.embedding.engine.dart.DartMessenger.a:20
	io.flutter.embedding.engine.dart.DartMessenger.b:0
	io.flutter.embedding.engine.dart.c.run:12
	android.os.Handler.handleCallback:873
	android.os.Handler.dispatchMessage:99
	android.os.Looper.loop:193
	android.app.ActivityThread.main:7168
	java.lang.reflect.Method.invoke:-2
	com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run:493
	com.android.internal.os.ZygoteInit.main:858

发生时间 ：2022-04-25 09:30:40 736		索引 ：100000018
49.4.35.47
调用SDK：华为HMS核心功能
调用堆栈：
	java.net.Inet4Address.getAddress:340
	libcore.io.Linux.connect:-2
	libcore.io.BlockGuardOs.connect:118
	libcore.io.IoBridge.connectErrno:168
	libcore.io.IoBridge.connect:129
	java.net.PlainSocketImpl.socketConnect:137
	java.net.AbstractPlainSocketImpl.doConnect:390
	java.net.AbstractPlainSocketImpl.connectToAddress:230
	java.net.AbstractPlainSocketImpl.connect:212
	java.net.SocksSocketImpl.connect:436
	java.net.Socket.connect:621
	com.android.okhttp.internal.Platform.connectSocket:145
	com.android.okhttp.internal.io.RealConnection.connectSocket:141
	com.android.okhttp.internal.io.RealConnection.connect:112
	com.android.okhttp.internal.http.StreamAllocation.findConnection:184
	com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection:126
	com.android.okhttp.internal.http.StreamAllocation.newStream:95
	com.android.okhttp.internal.http.HttpEngine.connect:281
	com.android.okhttp.internal.http.HttpEngine.sendRequest:224
	com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute:467
	com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect:133
	com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect:89
	com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect:26
	com.huawei.hms.framework.network.grs.g.g.k:94
	com.huawei.hms.framework.network.grs.g.g.call:0
	java.util.concurrent.FutureTask.run:266

**Comment by Xuejiao-Shi** [comment]
您好，建议参考链接排查是否触发了自动初始化：https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/basiccapabilities-0000001050417999#section1560112301542

**Comment by tenutos** [comment]
经过反复确认，链接中提供的2个自动初始化的方法均未调用。

**Comment by tenutos** [comment]
再次确认，在弹窗请求用户授权前，应用未进行任何涉及到native的功能，我这边已经同时将问题反馈给小米应用市场审核外包的第三方（捷兴信源），等待对方二次确认。对方给的堆栈当中，含有hms相关的关键字，麻烦大佬们帮忙排查下看看，使用的flutter插件版本：uawei_push 6.3.0+302。

**Comment by Xuejiao-Shi** [comment]
您好，问题已在最新版本修复，请更新至最新版本试下，应该可以解决您的问题：https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides-V1/version-change-history-0000001050417995-V1

**Comment by Xuejiao-Shi** [comment]
您好，问题已在最新版本修复，请更新至最新版本试下，应该可以解决您的问题：https://pub.dev/packages/huawei_push

**Comment by tenutos** [comment]
感谢，我这几天测试一下。

**Comment by tenutos** [comment]
提交给对方，回复说问题仍然存在。

**Comment by tenutos** [comment]
尝试了这些方法：

**Comment by tenutos** [comment]
1.await Push.isAutoInitEnabled(); =>false
2.使用=>(import 'package:huawei_push/huawei_push.dart' deferred as huawei;)延迟加载，在应用中啥代码都不写时，Logcat中仍然会输出很多hmssdk的相关调用(该方式未打包给对方测试。)
3.彻底移除huawei_push库，Logcat中不在输出任何hmssdk的信息(该方式未打包给对方测试。)

把huawei_push库移除，应该能解决这个问题，但是业务中关于推送相关的逻辑改动会比较大，其他型号的安卓机中使用了库中的一些方法，希望官方能解决。感谢！

**Comment by tenutos** [comment]
又进行了一些尝试：
发现在flutter代码执行之前，其实hmssdk就做了一些操作：
I/SecurityComp10105310: SecureX509TrustManager(23697): checkServerTrusted succeed ,root ca issuer is : CN=Huawei CBG Root CA, OU=Huawei CBG, O=Huawei, C=CN
W/NetworkKit_g(23697): NetworkKit_GRS_RequestController-Task_1 -->NetworkKit_GRS_RequestController-Task_3|null|com.huawei.hms.framework.network.grs.g.g|call|232|RequestCallableV2 run task catch IOException
W/NetworkKit_g(23697): java.io.InterruptedIOException: t*r*a* *n*e*r*p*e*
W/NetworkKit_g(23697): 	at com.android.okhttp.okio.Timeout.throwIfReached(Timeout.java:147)
W/NetworkKit_g(23697): 	at com.android.okhttp.okio.Okio$1.write(Okio.java:75)
W/NetworkKit_g(23697): 	at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:157)
W/NetworkKit_g(23697): 	at com.android.okhttp.okio.RealBufferedSink.flush(RealBufferedSink.java:222)
W/NetworkKit_g(23697): 	at com.android.okhttp.internal.http.Http1xStream.finishRequest(Http1xStream.java:163)
W/NetworkKit_g(23697): 	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:748)
W/NetworkKit_g(23697): 	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
W/NetworkKit_g(23697): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
/D:/flutter/.pub-cache/git/knife-b57035da3d8f52a35ca6c4152927469603ea2e26/lib/knife/view/toast.dart:348:30: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
      locale: WidgetsBinding.instance!.window.locale,
 这时根本还没到main方法中来，main入口中的打印此时都还没有输出。

**Comment by tenutos** [comment]
![image](https://user-images.githubusercontent.com/31977578/172837990-2b7aee54-be95-422c-a87b-85cbc1c349b3.png)
麻烦修复下吧，现在连你们家自己的应用市场都驳回来了。

**Comment by tenutos** [comment]
![image](https://user-images.githubusercontent.com/31977578/172838331-8791eb27-4c16-4e8c-a828-c1bf61ff0980.png)

**Comment by Xuejiao-Shi** [comment]
您好，感谢您提供此次报障线索，此问题需要进一步定位，请通过提单与我们联系，技术人员会将修改方式发给您。
提单链接：https://developer.huawei.com/consumer/cn/support/feedback/#/

**Comment by tenutos** [comment]
好的
