### ISSUE TITLE
[hms_account_kit] Crash on login attempt

### ISSUE THREAD

**Issue by andreagr** [HMS-Core/hms-flutter-plugin#24]
I am trying to implement the Account Kit, and I followed all the integration steps as presented in the official documentation.
I already have the analytics kit configured and working.

When I try to start the login with the Huawei Kit I get this:

```
D/ActivityThread(10801): add activity client record, r= ActivityRecord{f78510 token=android.os.BinderProxy@63ade0c {com.greenflea/com.huawei.hms.hwid.internal.ui.activity.HwIdSignInHubActivity}} token= android.os.BinderProxy@63ade0c
D/OpenGLRenderer(10801): disableOutlineDraw is true
D/mali_winsys(10801): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/HiTouch_PressGestureDetector(10801): onAttached, package=com.greenflea, windowType=1, mHiTouchRestricted=false
I/HwViewRootImpl(10801): removeInvalidNode all the node in jank list is out of time
W/ActivityThread(10801): handleWindowVisibility: no activity for token android.os.BinderProxy@6649172
V/ActivityThread(10801): callActivityOnCreate
I/HMSSDK_Util(10801): available exist: true
I/HMSSDK_HMSPackageManager(10801): current versionCode:50002301, minimum version requirements: 30000000
I/HMSSDK_HMSPackageManager(10801): MinApkVersion is disabled.
I/HMSSDK_ForegroundBusDelegate(10801): startApkHubActivity
D/ActivityThread(10801): add activity client record, r= ActivityRecord{8c2958 token=android.os.BinderProxy@6649172 {com.greenflea/com.huawei.hms.activity.BridgeActivity}} token= android.os.BinderProxy@6649172
D/HiTouch_PressGestureDetector(10801): onAttached, package=com.greenflea, windowType=1, mHiTouchRestricted=false
D/mali_winsys(10801): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/OpenGLRenderer(10801): disableOutlineDraw is true
W/com.greenflea(10801): Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (greylist,core-platform-api, linking, allowed)
I/HMSSDK_ForegroundBusDelegate(10801): succeedReturn
I/HMSSDK_BridgeActivity(10801): Enter finish.
I/HMSSDK_[HUAWEIIDSDK]HwIdSignInClientHub(10801): report: api=hwid.signinintentversion=40004300
W/libEGL  (10801): EGLNativeWindowType 0x7632d482d0 disconnect failed
I/flutter (10801): PlatformException(101, 6003: , , null)
D/ActivityThread(10801): Remove activity client record, r= ActivityRecord{8c2958 token=android.os.BinderProxy@6649172 {com.greenflea/com.huawei.hms.activity.BridgeActivity}} token= android.os.BinderProxy@6649172
D/ActivityThread(10801): Remove activity client record, r= ActivityRecord{f78510 token=android.os.BinderProxy@63ade0c {com.greenflea/com.huawei.hms.hwid.internal.ui.activity.HwIdSignInHubActivity}} token= android.os.BinderProxy@63ade0c
W/libEGL  (10801): EGLNativeWindowType 0x7632d47290 disconnect failed
W/ConnectionTracker(10801): Exception thrown while unbinding
W/ConnectionTracker(10801): java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.measurement.internal.zzjf@29870b4
W/ConnectionTracker(10801): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1832)
W/ConnectionTracker(10801): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1880)
W/ConnectionTracker(10801): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:741)
W/ConnectionTracker(10801): 	at com.google.android.gms.common.stats.ConnectionTracker.zza(com.google.android.gms:play-services-basement@@17.3.0:55)
W/ConnectionTracker(10801): 	at com.google.android.gms.common.stats.ConnectionTracker.unbindService(com.google.android.gms:play-services-basement@@17.3.0:50)
W/ConnectionTracker(10801): 	at com.google.android.gms.measurement.internal.zzin.zzah(com.google.android.gms:play-services-measurement-impl@@17.4.1:246)
W/ConnectionTracker(10801): 	at com.google.android.gms.measurement.internal.zzin.zzam(com.google.android.gms:play-services-measurement-impl@@17.4.1:263)
W/ConnectionTracker(10801): 	at com.google.android.gms.measurement.internal.zzin.zzc(com.google.android.gms:play-services-measurement-impl@@17.4.1:330)
W/ConnectionTracker(10801): 	at com.google.android.gms.measurement.internal.zziq.zza(com.google.android.gms:play-services-measurement-impl@@17.4.1:2)
W/ConnectionTracker(10801): 	at com.google.android.gms.measurement.internal.zzah.run(com.google.android.gms:play-services-measurement-impl@@17.4.1:7)
W/ConnectionTracker(10801): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/ConnectionTracker(10801): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ConnectionTracker(10801): 	at com.google.android.gms.measurement.internal.zzfy.run(com.google.android.gms:play-services-measurement-impl@@17.4.1:21)

```

I have noticed the `PlatformException(101, 6003: , , null)` line, but I have the fingerprint correctly added to the developer console.

The code I'm using to login is the following:
```void _huaweiAccountLoginLoader() async {
    print('\n check 02 : login mode \n ');
    AuthParamHelper helper = new AuthParamHelper();
    // You can set many options by using cascades
    //helper..setEmail();
    helper
      ..setIdToken()
      ..setAuthorizationCode()
      ..setAccessToken()
      ..setProfile()
      ..setEmail()
      ..setId();
    try {
      // Make sure you handle the possible exceptions.

      final AuthHuaweiId authHuaweiId = await HmsAccount.signIn(helper);

      print(authHuaweiId.email);
    } on Exception catch (e) {
      print(e.toString());
    }
  }
```

EDIT:

After adding the SHA-256 to the console, now I get this error: `I/flutter (22420): PlatformException(101, 10: , , null)`

**Comment by andreagr** [comment]
Adding the following line to in the android/app/build.gradle file solved the issue, but I don't know why: 

```
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.google.android.gms:play-services-basement:17.4.0'
    implementation 'com.google.firebase:firebase-analytics:17.5.0'
    implementation 'com.google.firebase:firebase-messaging:20.3.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.android.support:multidex:1.0.3'
}
```

**Comment by sinan-aktepe** [comment]
Hi @andreagr ,
I created a flutter project and used huawei_account plugin with huawei_analytics plugin. I ran the application on Huawei P30 Smart and Sony Xperia XZ1 (HMS is installed) phones to make sure everything is ok. There's not any kind of problem so far.

Can you check if:

- Account kit is enabled in your AppGallery Connect project,
- Your agcconnect-services.json file is up to date,
- And HMS Core version in your device is up to date?

And can you share the pubspec.yaml file with the dependencies you use?
