### ISSUE TITLE
Unhandled exception in huawei_analytics 6.5.0+301

### ISSUE THREAD

**Issue by yom-ko** [HMS-Core/hms-flutter-plugin#262]
**Description**
I encounter an unhandled exception in package `huawei_analytics: 6.5.0+301` upon `onEvent` method call.

**Expected behavior**
No exceptions

**Current behavior**
There is an exception `java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference`

**Logs**
```
E/MethodChannel#com.huawei.hms.flutter.analytics(17772): Failed to handle method call
E/MethodChannel#com.huawei.hms.flutter.analytics(17772): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/MethodChannel#com.huawei.hms.flutter.analytics(17772): 	at com.huawei.hms.flutter.analytics.utils.MapUtils.mapToBundle(MapUtils.java:126)
E/MethodChannel#com.huawei.hms.flutter.analytics(17772): 	at com.huawei.hms.flutter.analytics.HMSAnalyticsModule.onEvent(HMSAnalyticsModule.java:117)
E/MethodChannel#com.huawei.hms.flutter.analytics(17772): 	at com.huawei.hms.flutter.analytics.handler.HMSAnalyticsMethodCallHandler.onMethodCall(HMSAnalyticsMethodCallHandler.java:99)
E/MethodChannel#com.huawei.hms.flutter.analytics(17772): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#com.huawei.hms.flutter.analytics(17772): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#com.huawei.hms.flutter.analytics(17772): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#com.huawei.hms.flutter.analytics(17772): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#com.huawei.hms.flutter.analytics(17772): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#com.huawei.hms.flutter.analytics(17772): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#com.huawei.hms.flutter.analytics(17772): 	at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#com.huawei.hms.flutter.analytics(17772): 	at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#com.huawei.hms.flutter.analytics(17772): 	at android.app.ActivityThread.main(ActivityThread.java:7870)
E/MethodChannel#com.huawei.hms.flutter.analytics(17772): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#com.huawei.hms.flutter.analytics(17772): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#com.huawei.hms.flutter.analytics(17772): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
I/HMSAnalyticsMethodCallHandler(17772):  Running method : onEvent
```

**Environment**
 - Platform: Flutter
 - Kit: Analytics
 - Kit Version: 6.8.0.300
 - OS Version Android 12

**Other**
I double-checked the integration against the docs and it seems to be OK, so this is probably the package's internal bug.

**Comment by huseyinerenguler** [comment]
Hi @yom-ko 

In Native Android Analytics Kit, when you send an empty list, the SDK won't process the key-value as default. So it won't show up on the AppGallery console. Hence, the Flutter Analytics Plugin **doesn't expect empty list** for a "value" of key.

For now, you may check your list whether it is empty or not on your side. We will definitely add this check to our next major version.

**Comment by sinemsevilmis** [comment]
Hi @yom-ko,

Huawei Analytics Kit 6.9.0+302 has been released. We added check of whether list empty or not. Please check [pub.dev](https://pub.dev/packages/huawei_analytics).

Thank you for your interest.

**Comment by yom-ko** [comment]
> Hi @yom-ko,
> 
> Huawei Analytics Kit 6.9.0+302 has been released. We added check of whether list empty or not. Please check [pub.dev](https://pub.dev/packages/huawei_analytics).
> 
> Thank you for your interest.

Thanks!
