### ISSUE TITLE
Crash when implementing huwawei_iap

### ISSUE THREAD

**Issue by bkleineibst** [HMS-Core/hms-flutter-plugin#293]
**Description**
I am trying to add huawei_iap to a new flutter app. As soon as I call the isEnvReady() function, the app crashes.

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  try {
    final IsEnvReadyResult result = await IapClient.isEnvReady();
  } on Exception catch (e) {
    debugPrint("IAP: isEnvReady() exception: $e");
  }

  runApp(const MyApp());
}
```

**Expected behavior**
The app shouldn't crash and should either return the result or throw a catchable error.

**Current behavior**
The app crashed.

**Logs**
 2023-05-10 20:37:42 12795-12795/? D/HMS: HMS onActivityResult(1, -1)
 2023-05-10 20:37:42 12795-12795/? D/HMS: result: io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1@941660f, requestType: 222
 2023-05-10 20:37:42 12795-12795/? D/HMS: RESULT_OK
 2023-05-10 20:37:42 12795-12795/? D/HMS: REQUEST_IS_ENVIRONMENT_READY: 60000
 2023-05-10 20:37:42 12795-12795/? D/HMS: Error: Can not log in.
 2023-05-10 20:37:42 722-722/? I/SurfaceFlinger: doComposeSurfaces Skipping draw when recording screen 5
 2023-05-10 20:37:42 722-722/? I/SurfaceFlinger: doComposeSurfaces Skipping draw when recording screen 5
 2023-05-10 20:37:42 722-722/? I/SurfaceFlinger: Draw one black Layer when SecureScreenRecord 4
 2023-05-10 20:37:42 12795-12795/? I/BlockMonitor: dispatchingThrewException In MainThread
 2023-05-10 20:37:42 12795-12795/? D/AndroidRuntime: Shutting down VM
 2023-05-10 20:37:42 20703-12792/? I/HiAdKit.DC.PageSwitchEvent:  switch is off
 2023-05-10 20:37:42 1569-1668/? I/HwAudioServiceEx: ComponentInfo : className = com.huawei.hms.runtimekit.stub.HMSKitStandardC2NETransparentActivity1, flag = onPause, isHomeActivity = , isTop = false
 2023-05-10 20:37:42 12795-12795/? I/QarthLog: [PatchStore] createDisableExceptionQarthFile
 2023-05-10 20:37:42 12795-12795/? I/QarthLog: [PatchStore] create disable file for com.example.hms uid is 18742
 2023-05-10 20:37:42 20703-12792/? I/HiAdKit.DC.PaymentPageSwitchEvent:  switch is off
 2023-05-10 20:37:42 1569-2051/? W/HwAudioServiceEx: SoundEffectState bundle get reserved is invalid
 2023-05-10 20:37:42 1569-2051/? I/HwAudioServiceEx: sendAppKilledIntentForKit, isKitPackageOnPause = false, isKitPackageKill = false, isKitPackageOnResume = false
 2023-05-10 20:37:42 20703-12792/? I/HiAdKit.DC.LiteAppPageSwitchEvent:  switch is off
--------- beginning of crash
 2023-05-10 20:37:42 12795-12795/? E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.example.hms, PID: 12795
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { (has extras) }} to activity {com.example.hms/com.example.hms.MainActivity}: java.lang.IllegalStateException: Reply already submitted
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5615)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5656)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2475)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8401)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1087)
Caused by: java.lang.IllegalStateException: Reply already submitted
	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(Unknown Source:35)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(Unknown Source:14)
	at com.huawei.hms.flutter.iap.MethodCallHandlerImpl.onActivityResult(Unknown Source:230)
	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(Unknown Source:25)
	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(Unknown Source:13)
	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(Unknown Source:51)
	at io.flutter.embedding.android.FlutterActivity.onActivityResult(Unknown Source:10)
	at android.app.Activity.dispatchActivityResult(Activity.java:8448)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5608)
	... 11 more
 2023-05-10 20:37:42 12795-12838/? I/flutter: HMS: isEnvReady() exception: PlatformException(ERR_CAN_NOT_LOG_IN, Can not log in., null, null)
 2023-05-10 20:37:42 696-1375/? I/DE H FCThermal: checkAndWaitActive:314: Sampling is active.

**Environment**
 - Platform: Flutter
 - Kit: IAP
 - Kit Version: ^6.4.0+302 (same issue with master branch)
 - OS Version: P40 EMUI 11.0.1 on Cloud Debugging
 - Platform version: 3.7.12

**Other**
I am testing on cloud debugging with a P40 running EMUI 11.0.1.
I have gone through the required steps in the guide, and placed agconnect-services.json in my project.
Initially tried this in an existing app, but when I got this error, I tried by creating a new app, with no other dependencies, except for huawei_iap.

**Comment by simonakad** [comment]
Hi @bkleineibst 
I encountered this error when I cancel the login flow during the  `IapClient.isEnvReady()` method execution. The "Reply already submitted" error happens when the same `result` is being used twice for sending an answer to the Dart side. 

After changing the case of `onActivityResult` in `IAP\android\src\main\java\com\huawei\hms\flutter\iap\MethodCallHandlerImpl.java` , which is;
```java
case REQUEST_IS_ENVIRONMENT_READY:
    final int returnCode = data.getIntExtra("returnCode", 1);
    if (returnCode != 0) {
        result.error(Errors.LOG_IN.getErrorCode(), Errors.LOG_IN.getErrorMessage(), null);
    }
    result.success("LOGGED_IN");
    break;
```

**to**

```java
case REQUEST_IS_ENVIRONMENT_READY:
    final int returnCode = data.getIntExtra("returnCode", 1);
    if (returnCode == 0) {
        result.success("LOGGED_IN"); 
        return true;                          
    } 
    result.error(Errors.LOG_IN.getErrorCode(), Errors.LOG_IN.getErrorMessage(), null);
    return true;
``` 
It worked normally 🎉

If it is also works in your case, I guess the developers may change the plugin code accordingly.

**Comment by bkleineibst** [comment]
Thanks @simonakad,

That was the issue. I just added a `break` after the `result.error()`, for the same effect.

**Comment by ozkulbeng** [comment]
Glad that it was solved, we will add the necessary changes in our next major update.

**Comment by deakjahn** [comment]
@ozkulbeng Considering that this is a breaking change that kills the IAP in already existing apps, could we kindly suggest that you don't wait for a **major** update? :-)

**Comment by ozkulbeng** [comment]
Hello dear developers,
This issue has been resolved with the latest version of huawei_iap. Please use the [newest version of the plugin](https://pub.dev/packages/huawei_iap/versions/6.10.0+300) in your apps.

Thank you for your interest in our plugins.
