### ISSUE TITLE
[Location] Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

### ISSUE THREAD

**Issue by EArminjon** [HMS-Core/hms-flutter-plugin#312]
**Description**
Api seems not be compatible with android 12+

```dart
FusedLocationProviderClient().requestLocationUpdates(LocationRequest());
```

**Expected behavior**
I would like to see the Location update well requested without issues.

**Current behavior**
Api fail 

**Logs**
```
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): Failed to handle method call
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): java.lang.IllegalArgumentException: com.my-flutter-app.uat: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at android.app.PendingIntent.checkPendingIntent(PendingIntent.java:428)
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:731)
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at android.app.PendingIntent.getBroadcast(PendingIntent.java:718)
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at com.huawei.hms.flutter.location.handlers.FusedLocationMethodHandler.buildLocationIntent(FusedLocationMethodHandler.java:291)
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at com.huawei.hms.flutter.location.handlers.FusedLocationMethodHandler.requestLocationUpdates(FusedLocationMethodHandler.java:138)
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at com.huawei.hms.flutter.location.handlers.FusedLocationMethodHandler.onMethodCall(FusedLocationMethodHandler.java:321)
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at android.os.Handler.handleCallback(Handler.java:958)
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at android.os.Looper.loopOnce(Looper.java:205)
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at android.os.Looper.loop(Looper.java:294)
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/MethodChannel#com.huawei.flutter.location/fusedlocation_methodchannel(16784): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

```

**Environment**
 - Platform: Flutter 3.7.12
 - Kit: huawei_location
 - Kit Version 6.11.0+301
 - OS Version Android API 34

**Comment by EArminjon** [comment]
@ozkulbeng  can you take a look please :'( ? This prevent us to deploy on the Huawei store.

**Comment by ozkulbeng** [comment]
Hello @EArminjon 
This issue has been resolved with the new version (6.12.0+300) of [huawei_location](https://pub.dev/packages/huawei_location). Please use the latest version.
Thank you for your interest in our plugins.

**Comment by EArminjon** [comment]
Hello @ozkulbeng ,

Thank you for the update but something is broken: 

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkUat_rexelseDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class org.bouncycastle.LICENSE found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
     Duplicate class org.bouncycastle.asn1.ASN1ApplicationSpecific found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
     Duplicate class org.bouncycastle.asn1.ASN1ApplicationSpecificParser found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
     Duplicate class org.bouncycastle.asn1.ASN1BitString found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
     Duplicate class org.bouncycastle.asn1.ASN1Boolean found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
     Duplicate class org.bouncycastle.asn1.ASN1Choice found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
     Duplicate class org.bouncycastle.asn1.ASN1Encodable found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
     Duplicate class org.bouncycastle.asn1.ASN1EncodableVector found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
     Duplicate class org.bouncycastle.asn1.ASN1Encoding found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
     Duplicate class org.bouncycastle.asn1.ASN1Enumerated found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
     Duplicate class org.bouncycastle.asn1.ASN1Exception found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
     Duplicate class org.bouncycastle.asn1.ASN1External found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
     Duplicate class org.bouncycastle.asn1.ASN1GeneralizedTime found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
     Duplicate class org.bouncycastle.asn1.ASN1Generator found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
     Duplicate class org.bouncycastle.asn1.ASN1InputStream found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
     Duplicate class org.bouncycastle.asn1.ASN1Integer found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
     Duplicate class org.bouncycastle.asn1.ASN1Null found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
     Duplicate class org.bouncycastle.asn1.ASN1Object found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
     Duplicate class org.bouncycastle.asn1.ASN1ObjectIdentifier found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
     Duplicate class org.bouncycastle.asn1.ASN1ObjectIdentifier$OidHandle found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
     Duplicate class org.bouncycastle.asn1.ASN1OctetString found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
     Duplicate class org.bouncycastle.asn1.ASN1OctetStringParser found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
     Duplicate class org.bouncycastle.asn1.ASN1OutputStream found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
     Duplicate class org.bouncycastle.asn1.ASN1ParsingException found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
     Duplicate class org.bouncycastle.asn1.ASN1Primitive found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
     Duplicate class org.bouncycastle.asn1.ASN1Sequence found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
     Duplicate class org.bouncycastle.asn1.ASN1Sequence$1 found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
     Duplicate class org.bouncycastle.asn1.ASN1Sequence$2 found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)

```

**Comment by EArminjon** [comment]
Hello @ozkulbeng, up  ?
