### ISSUE TITLE
huawei_push java.lang.NullPointerException

### ISSUE THREAD

**Issue by bkleineibst** [HMS-Core/hms-flutter-plugin#315]
I am seeing the following error in Crashlytics logs, but am not sure what the cause is:
```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.view.FlutterCallbackInformation.callbackLibraryPath' on a null object reference
       at io.flutter.embedding.engine.dart.DartExecutor$DartCallback.toString(DartExecutor.java:421)
       at java.lang.String.valueOf(String.java:2924)
       at java.lang.StringBuilder.append(StringBuilder.java:132)
       at io.flutter.embedding.engine.dart.DartExecutor.executeDartCallback(DartExecutor.java:175)
       at com.huawei.hms.flutter.push.backgroundmessaging.FlutterBackgroundRunner.lambda$startBgIsolate$0$com-huawei-hms-flutter-push-backgroundmessaging-FlutterBackgroundRunner(FlutterBackgroundRunner.java:130)
       at com.huawei.hms.flutter.push.backgroundmessaging.FlutterBackgroundRunner$$ExternalSyntheticLambda1.run(:8)
       at android.os.Handler.handleCallback(Handler.java:900)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:8349)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

It seems to happen when a background push notification is received, but not on all devices with the app. Seems to happen on a number of different types of phones and various OS versions.

I don't see these errors when I test on Cloud Debugging devices, even if the app is in the background.

The code in the startBgIsolate function looks very similar to that in FlutterFirebaseMessagingBackgroundExecutor and I am not seeing the same issue when using that on non HMS devices.

I found this similar issue (https://github.com/HMS-Core/hms-flutter-plugin/issues/240), but have done what is suggested there and it doesn't seem to make a difference.

I also found a similar crash with firebase (https://github.com/firebase/flutterfire/issues/9345), that was resolved by changing the way the FlutterLoader is created. 

And another similar issue for background_fetch, that proposed adding the `android:name="io.flutter.app.FlutterApplication"`. I currently have `android:name="${applicationName}"`.

I still need to try these 2 options with release, but the fact that the firebase release doesn't have this issue might imply that something else needs to be changed with this plugin.

Any suggestions?

**Comment by bkleineibst** [comment]
> I also found a similar crash with firebase (https://github.com/firebase/flutterfire/issues/9345), that was resolved by changing the way the FlutterLoader is created.

It's early days, but this seems to have helped:
```
        FlutterLoader flutterLoader = FlutterInjector.instance().flutterLoader();
        Handler mainHandler = new Handler(Looper.getMainLooper());
        Runnable runnable = () -> {
            flutterLoader.startInitialization(Objects.requireNonNull(PluginContext.getContext()));
            flutterLoader.ensureInitializationCompleteAsync(PluginContext.getContext(), null, mainHandler, () -> {
```

I'm not sure it is because I moved the instance flutterLoader outside the callback function, to match where it is in FlutterFirebaseMessagingBackgroundExecutor, or if it is because I have changed it to use FlutterInjector, as per the above issue.

**Comment by bkleineibst** [comment]
> I also found a similar crash with firebase (https://github.com/firebase/flutterfire/issues/9345), that was resolved by changing the way the FlutterLoader is created.

This doesn't seem to help:
```
        FlutterLoader flutterLoader = FlutterInjector.instance().flutterLoader();
        Handler mainHandler = new Handler(Looper.getMainLooper());
        Runnable runnable = () -> {
            flutterLoader.startInitialization(Objects.requireNonNull(PluginContext.getContext()));
            flutterLoader.ensureInitializationCompleteAsync(PluginContext.getContext(), null, mainHandler, () -> {
```

I moved the flutterLoader instance outside the callback function, to match where it is in FlutterFirebaseMessagingBackgroundExecutor, and also changed it to use FlutterInjector, as per the above issue.

**Comment by Hayolox** [comment]
Hi [bkleineibst](https://github.com/bkleineibst), Is this problem resolved? I experienced the same problem
