### ISSUE TITLE
Click on the "Legal" link that it's over the map, crashes the app

### ISSUE THREAD

**Issue by jjchiw** [HMS-Core/hms-flutter-plugin#48]
**Description**
Click on the "Legal" link that it's over the map, crashes the app

I had to remove `CustomActionBar` from `HuaweiMapDemo` Widget in order to view the "Legal" link

**Expected behavior**
What you expected to happen？
Not really sure what should happen.... show the "Legal" stuff in a dialog it seems

**Current behavior**
Crashes the app

**Screenshots**
![vid](https://user-images.githubusercontent.com/642319/101354497-8f46da80-3895-11eb-8a59-d9930212ac9e.gif)

**Logs**
```
V/AudioManager( 3062): querySoundEffectsEnabled...
I/HmsMapKit_GrsCache_80( 3062): GRS copyright address : https://developer.huawei.com/
D/HmsMapKit_CopyrightUtils_40( 3062): getCopyrightUrl: https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/map-data-copyright-statement-0000001050166543
I/BlockMonitor( 3062): dispatchingThrewException In MainThread
D/AndroidRuntime( 3062): Shutting down VM
I/QarthLog( 3062): [PatchStore] createDisableExceptionQarthFile
I/QarthLog( 3062): [PatchStore] create disable file for com.app uid is 10155
E/AndroidRuntime( 3062): FATAL EXCEPTION: main
E/AndroidRuntime( 3062): Process: com.app, PID: 3062
E/AndroidRuntime( 3062): java.lang.ClassCastException: $Proxy1 cannot be cast to android.view.WindowManagerImpl
E/AndroidRuntime( 3062): 	at android.view.Window.setWindowManager(Window.java:780)
E/AndroidRuntime( 3062): 	at android.view.Window.setWindowManager(Window.java:762)
E/AndroidRuntime( 3062): 	at android.app.Dialog.<init>(Dialog.java:298)
E/AndroidRuntime( 3062): 	at android.app.Dialog.<init>(Dialog.java:247)
E/AndroidRuntime( 3062): 	at com.huawei.hms.maps.provider.util.maj.<init>(Unknown Source:0)
E/AndroidRuntime( 3062): 	at com.huawei.hms.maps.provider.util.mab.a(Unknown Source:10)
E/AndroidRuntime( 3062): 	at com.huawei.hms.maps.provider.util.mab.lambda$-kTcvCeS_2CWiXGIoiKf5UZv2Uo(Unknown Source:0)
E/AndroidRuntime( 3062): 	at com.huawei.hms.maps.provider.util.-$$Lambda$mab$-kTcvCeS_2CWiXGIoiKf5UZv2Uo.onClick(Unknown Source:0)
E/AndroidRuntime( 3062): 	at android.view.View.performClick(View.java:7217)
E/AndroidRuntime( 3062): 	at android.view.View.performClickInternal(View.java:7191)
E/AndroidRuntime( 3062): 	at android.view.View.access$3500(View.java:828)
E/AndroidRuntime( 3062): 	at android.view.View$PerformClick.run(View.java:27679)
E/AndroidRuntime( 3062): 	at android.os.Handler.handleCallback(Handler.java:900)
E/AndroidRuntime( 3062): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/AndroidRuntime( 3062): 	at android.os.Looper.loop(Looper.java:219)
E/AndroidRuntime( 3062): 	at android.app.ActivityThread.main(ActivityThread.java:8349)
E/AndroidRuntime( 3062): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3062): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime( 3062): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
I/HianalyticsSDK( 3062): [2020-12-07 13:57:55.014 I/hianalytics/HianalyticsSDK 3062:1 null:13] HiAnalyticsDataManager.getInitFlag(String tag) is execute.
W/HianalyticsSDK( 3062): [2020-12-07 13:57:55.015 W/hianalytics/HianalyticsSDK 3062:1 null:7] getInstanceByTag(): TAG: hms_hwid not found.
I/HianalyticsSDK( 3062): [2020-12-07 13:57:55.015 I/hianalytics/HianalyticsSDK 3062:1 null:13] HiAnalyticsDataManager.getInitFlag(String tag) is execute.
W/HianalyticsSDK( 3062): [2020-12-07 13:57:55.015 W/hianalytics/HianalyticsSDK 3062:1 null:7] getInstanceByTag(): TAG: hms_hwid not found.
I/HmsMapKit_CrashHandler_135( 3062): uncaughtException
E/HmsMapKit_CrashHandler_108( 3062): handleException: $Proxy1 cannot be cast to android.view.WindowManagerImpl
D/HmsMapKit_CrashHandler_80( 3062): logLength is 0
E/HmsMapKit_CrashHandler_136( 3062): uncaughtException stacktrace is
E/HmsMapKit_CrashHandler_137( 3062): deviceModel is JNY-LX1 emuiVersion is EmotionUI_10.1.0 packageName is com.app rom version is JNY-L21 10.1.0.243(C432E1R6P1)
E/HmsMapKit_ErrorTraceLogPusher_145( 3062): cache error trace log : ErrorTraceLogDTO{ scenario = UNCAUGHT_EXCEPTION', message=''}
D/HmsMapKit_ErrorTraceLogPusher_1092( 3062): analyticsInstance.onEvent(), eventId is map_errorlog_report, valueMap.size() is 12
I/HiAnalytics/event( 3062): [2020-12-07 13:57:55.018 I/hianalytics/HiAnalytics/event 3062:1 null:13] HiAnalyticsInstance.onEvent(int type, String eventId, Map<String, String> mapValue) is execute.TAG: hms_map,TYPE: 1
I/HmsMapKit_CrashHandler_135( 3062): manual action --
W/a       ( 3062): Cannot find The class:javax.crypto.Mac
I/Process ( 3062): Sending signal. PID: 3062 SIG: 9
Lost connection to device.
Exited (sigterm)

```

**Environment**
 - Platform: Flutter
 - Kit: Map
 - Kit Version current master source code
 - OS Version Android 10

**Comment by SerdarCanDev** [comment]
Hi @jjchiw , thank you for reporting the issue. 

The "Legal" link is implemented in the native Huawei Map SDK and unfortunately, it is not customizable. Originally, the button opens a Dialog Box which uses Web View inside it and redirects to the [Official Huawei Map Data Copyright Statement](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/map-data-copyright-statement-0000001050166543) document.

Huawei Map Flutter Plugin is a wrapper for native SDK and thus, depends on the "Platform View" of Flutter Engine, which causes the mentioned issue while trying to open a dialog box using presentation context.

Since `HuaweiMap` is a standalone widget, as a workaround, you may use `Stack` and `Align` widgets alongside `HuaweiMap` widget to cover the bottom left corner of the map. Implementing an `InkWell` widget with a transparent `Container` will let you navigate the user to "Copyright Statements". 

The sample code is as follows:
``` dart
//A widget to place different widgets on top of each other. 
Stack(children: [
          HuaweiMap(
              initialCameraPosition:
                  CameraPosition(target: _center, zoom: _zoom),
              onMapCreated: _onMapCreated,
             /*
                Other HuaweiMap configurations
             */
              ),
          // Use Align widget to cover the bottom left corner.
          Align(
            alignment: Alignment.bottomLeft,
            //A widget that makes its child tappable.
            child: InkWell(
              onTap: () {
                //Your navigation method.
                //It can either be a WebView to stick to the original implementation, 
                //or a new page that includes the Copyright Statement.
                log("tapped");
              },
              //Container with a fixed size. 
              child: Container(
                //Your size preferences for the tappable area. 
                height: 35,
                width: 60,
              ),
            ),
          ),
        ]),
```

Meanwhile, we are investigating the source of the issue and we will provide a solution with our next major release. Thank you for your patience.

**Comment by jjchiw** [comment]
Thanks..

Added the workaround. 

I decided to open the same url `HuaweiMap` was trying to open 

`launch("https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/map-data-copyright-statement-0000001050166543");`
