### ISSUE TITLE
Unable to display map in cloud debugging.

### ISSUE THREAD

**Issue by jasxir** [HMS-Core/hms-flutter-plugin#49]
**Description**
Have added to display Map as in the documentation. I'm not sure it's only related to cloud debugging.
Trying to display map on screen, cloud debugging using Mate 30 and Mate 30 Pro, P40

**Expected behavior**
Map Shown

**Current behavior**
Shows a grey screen and error as in the logs below.

**Logs**
android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
    at android.app.ContextImpl.startActivity(ContextImpl.java:1031)
    at android.app.ContextImpl.startActivity(ContextImpl.java:1000)
    at android.content.ContextWrapper.startActivity(ContextWrapper.java:383)
    at android.content.ContextWrapper.startActivity(ContextWrapper.java:383)
    at android.content.ContextWrapper.startActivity(ContextWrapper.java:383)
    at com.huawei.hms.maps.mbu.c(Unknown Source:59)
    at com.huawei.hms.maps.mbu.b(Unknown Source:8)
    at com.huawei.hms.maps.mbu.a(Unknown Source:15)
    at com.huawei.hms.maps.MapView$maa.createDelegate(Unknown Source:57)
    at com.huawei.hms.feature.dynamic.DeferredLifecycleHelper.a(Unknown Source:44)
    at com.huawei.hms.feature.dynamic.DeferredLifecycleHelper.onCreate(Unknown Source:5)
    at com.huawei.hms.maps.MapView.onCreate(Unknown Source:29)
    at com.huawei.hms.flutter.map.map.MapController.init(MapController.java:139)
    at com.huawei.hms.flutter.map.map.MapBuilder.build(MapBuilder.java:67)
    at com.huawei.hms.flutter.map.map.MapFactory.create(MapFactory.java:87)
    at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:186)
    at android.app.Dialog.dispatchOnCreate(Dialog.java:579)
    at android.app.Dialog.show(Dialog.java:397)
    at android.app.Presentation.show(Presentation.java:250)
    at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
    at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
    at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:207)
    at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
    at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
    at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
    at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
    at android.os.MessageQueue.nativePollOnce(Native Method)
    at android.os.MessageQueue.next(MessageQueue.java:363)
    at android.os.Looper.loop(Looper.java:173)
    at android.app.ActivityThread.main(ActivityThread.java:8147)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Environment**
 - Platform: Flutter
 - Kit: Map
 - Kit Version 5.0.3+302
 - OS Version: Android 10
 - Android Studio version 4.1.1
 - Platform version Flutter 1.22.4
 - Your Location/Region Malaysia

Thanks

**Comment by SerdarCanDev** [comment]
Hi @jasxir , thank you for reporting the issue. 

The issue originates from the HMS Core version handling of the Huawei Map Flutter Plugin. Regarding compatibility issues, our plugin requires the latest Hms Core version, yet fails to find it on the device. We identified the problem of the handling and will provide a solution in our next major release. 

Meanwhile, you may wait for the cloud devices to update their HMS Core versions or test our plugin on a real device with the latest HMS Core version.

**Comment by SerdarCanDev** [comment]
Hi @jasxir , I would like to inform you that the problem is solved and the new package is released. You can check updated version of the plugin from [pub.dev](https://pub.dev/packages/huawei_map).
