### ISSUE TITLE
HMS ML Liveness detection crashes after the built in activity disappears

### ISSUE THREAD

**Issue by petodavid** [HMS-Core/hms-flutter-plugin#58]
The application crashes after the native liveness detection activity disappears
**Logs**
**

```
Fatal Exception: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-54-thread-1
       at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:992)
       at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:736)
       at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:72)
       at io.flutter.embedding.engine.dart.DartExecutor$DefaultBinaryMessenger.send(DartExecutor.java:381)
       at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:179)
       at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:97)
       at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:83)
       at io.flutter.plugins.camera.DartMessenger.send(DartMessenger.java:56)
       at io.flutter.plugins.camera.DartMessenger.sendCameraErrorEvent(DartMessenger.java:39)
       at io.flutter.plugins.camera.Camera$4.onConfigured(Camera.java:324)
       at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.lambda$onConfigured$0$CallbackProxies$SessionStateCallbackProxy(CallbackProxies.java:53)
       at android.hardware.camera2.impl.-$$Lambda$CallbackProxies$SessionStateCallbackProxy$soW0qC12Osypoky6AfL3P2-TeDw.run(:4)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

**

**Environment**
 - OS Version : Android 10
 - Model: Nokia 5.3

**Firebase Crashclitycs Trace**
![Firebase Crashclitycs](https://i.ibb.co/nMC5559/Screenshot-2021-01-15-at-11-08-32.png)

**Comment by petodavid** [comment]
E/AndroidRuntime( 6120): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 6120): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:139)
E/AndroidRuntime( 6120): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:243)
E/AndroidRuntime( 6120): 	at com.huawei.hms.flutter.ml.body.LivenessDetectionMethodHandler$1.onFailure(LivenessDetectionMethodHandler.java:75)
E/AndroidRuntime( 6120): 	at com.huawei.hms.mlsdk.livenessdetection.MLLivenessCapture.a(MLLivenessCapture.java:5)
E/AndroidRuntime( 6120): 	at com.huawei.hms.mlsdk.livenessdetection.ui.LivenessDetectActivity.onBackPressed(LivenessDetectActivity.java:3)
E/AndroidRuntime( 6120): 	at com.huawei.hms.mlsdk.livenessdetection.A.onClick(LivenessDetectActivity.java:1)
E/AndroidRuntime( 6120): 	at android.view.View.performClick(View.java:7273)
E/AndroidRuntime( 6120): 	at android.view.View.performClickInternal(View.java:7237)
E/AndroidRuntime( 6120): 	at android.view.View.access$3600(View.java:802)
E/AndroidRuntime( 6120): 	at android.view.View$PerformClick.run(View.java:27910)
E/AndroidRuntime( 6120): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime( 6120): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime( 6120): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 6120): 	at android.app.ActivityThread.main(ActivityThread.java:7397)
E/AndroidRuntime( 6120): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6120): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 6120): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by sinan-aktepe** [comment]
Hi @petodavid ,
I ran the app on different devices to catch exceptions above but no errors occurred. Do you see these exceptions constantly?

**Comment by petodavid** [comment]
It was my mistake
