### ISSUE TITLE
when request to sign in  twice  , the app crash [huawei_account]

### ISSUE THREAD

**Issue by mustafa-707** [HMS-Core/hms-flutter-plugin#61]
**Description**
i just used the huawei account version 5.0.3+303 and i implemented the code like example

**Expected behavior**
i want to login and if the user not include the email to retry again with email , i will be more accept if there's a method thats makes the email required 
**Current behavior**
when i press to sign in it will navigate me to sign in screen and if i canceled or signed in it will gives a throw with message to make user re-try to login with email but i got this type of exception :

**Logs**
```
D/HMSLogger(31393): singleEventMap -> {result=0, apiName=isEnvReady, package=com.xxxx.main_app, costTime=283, service=FlutterIAP, appid=100599765, model=HWJNY, cpAppVersion=4.0.13, networkType=WIFI, version=5.0.2.300, callTime=1612448516350}
D/HMSLogger(31393): singleEventMap -> {result=0, apiName=revokeAuthorization, package=com.xxxx.main_app, costTime=466, service=FlutterAccount, appid=100599765, model=HWJNY, cpAppVersion=4.0.13, networkType=WIFI, version=5.0.3.302, callTime=1612448516606}
E/flutter (31393): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: type 'bool' is not a subtype of type 'LinkedHashMap<dynamic, dynamic>' in type cast
E/flutter (31393): #0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:159
E/flutter (31393): <asynchronous suspension>
E/flutter (31393): #1      MethodChannel.invokeMethod
package:flutter/…/services/platform_channel.dart:332
E/flutter (31393): #2      HmsAuthService.signIn
package:huawei_account/hmsauthservice/hms_auth_service.dart:43
E/flutter (31393): #3      SMLogin.huaweiLogIn
package:main_app/services/sm_login.dart:274
E/flutter (31393): <asynchronous suspension>
E/flutter (31393): #4      _LoginScreenState._huaweiButton.<anonymous closure>.<anonymous closure>
package:main_app/…/Login/login_screen.dart:299
E/flutter (31393): #5      _InkResponseState._handleTap
package:flutter/…/material/ink_well.dart:993
E/flutter (31393): #6      _InkResponseState.build.<anonymous closure>
package:flutter/…/material/ink_well.dart:1111
E/flutter (31393): #7      GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:183
E/flutter (31393): #8      TapGestureRecognizer.handleTapUp
package:flutter/…/gestures/tap.dart:598
E/flutter (31393): #9      BaseTapGestureRecognizer._checkUp
package:flutter/…/gestures/tap.dart:287
E/flutter (31393): #10     BaseTapGestureRecognizer.acceptGesture
package:flutter/…/gestures/tap.dart:259
E/flutter (31393): #11     GestureArenaManager.sweep
package:flutter/…/gestures/arena.dart:157
E/flutter (31393): #12     GestureBinding.handleEvent
package:flutter/…/gestures/binding.dart:362
E/flutter (31393): #13     GestureBinding.dispatchEvent
package:flutter/…/gestures/binding.dart:338
E/flutter (31393): #14     RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart:267
E/flutter (31393): #15     GestureBinding._handlePointerEvent
package:flutter/…/gestures/binding.dart:295
E/flutter (31393): #16     GestureBinding._flushPointerEventQueue
package:flutter/…/gestures/binding.dart:240
E/flutter (31393): #17     GestureBinding._handlePointerDataPacket
package:flutter/…/gestures/binding.dart:213
E/flutter (31393): #18     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (31393): #19     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (31393): #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (31393): #21     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (31393): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
```
**Environment**
 - Platform: Huawei nova 7i
 - Kit: huawei_account
 - Kit Version 5.0.3+303
 - OS Version Android 10
 - VS code

**Comment by sinan-aktepe** [comment]
Hi @mustafa-707, Thanks for reporting the issue.

We have spotted the error and it will be fixed on next release. Also you can follow these steps to create a workaround.

1. Go to **AuthServiceMethodHandler.java** file.
2. Then change the **onActivityResult** method as following:
```java
    @Override
    public boolean onActivityResult(int requestCode, int resultCode, Intent data) {
        final MethodChannel.Result incomingResult = mResult;
        mResult = null;

        Task<AuthHuaweiId> authIdTask = HuaweiIdAuthManager.parseAuthResultFromIntent(data);
        if (requestCode == rCode) {
            authIdTask.addOnSuccessListener(authId -> {

                HashMap<String, Object> resultMap = HwIdBuilder.createHwId(authId);
                Account account = authId.getHuaweiAccount();
                if (account != null) {
                    resultMap.put("account", HwIdBuilder.createAccount(account));
                }
                HMSLogger.getInstance(activity.getApplicationContext()).sendSingleEvent("signIn");
                if (incomingResult != null) {
                    incomingResult.success(resultMap);
                }
            }).addOnFailureListener(e -> {
                HMSLogger.getInstance(activity.getApplicationContext()).sendSingleEvent("signIn", String.valueOf(((ApiException) authIdTask.getException()).getStatusCode()));
                if (incomingResult != null) {
                    incomingResult.error(Constant.SIGN_IN_FAILURE, String.valueOf(((ApiException) authIdTask.getException()).getStatusCode()), e.getMessage());
                }
            });
        }
        return true;
    }
```

Run the application again and let us know how it goes.

**Comment by mustafa-707** [comment]
thank you
